{"name": "Проверка возвращаемого кода 409 при создании курьера с уже существующими данными", "status": "failed", "statusDetails": {"message": "AssertionError: assert (409 == 409 and 'Этот логин у...буйте другой.' == 'Этот логин уже используется'\n +  where 409 = <Response [409]>.status_code\n  \n  - Этот логин уже используется\n  + Этот логин уже используется. Попробуйте другой.)", "trace": "self = <test_create_courier.TestCreateCourier object at 0x110259160>, create_courier_data = {'login': '3qcrq58b6c', 'password': 'xe8jy0sg3y'}, login_and_delete_courier = <Response [200]>\n\n>   ???\nE   AssertionError: assert (409 == 409 and 'Этот логин у...буйте другой.' == 'Этот логин уже используется'\nE    +  where 409 = <Response [409]>.status_code\nE     \nE     - Этот логин уже используется\nE     + Этот логин уже используется. Попробуйте другой.)\n\n/Users/flowforme/stud/pythonProject/tests/test_create_courier.py:21: AssertionError"}, "start": 1723291436939, "stop": 1723291437341, "uuid": "65fbb1b1-a700-44d8-b08b-f6824d08f415", "historyId": "cbbc55ff1902e8e4133cab085137f5b9", "testCaseId": "cbbc55ff1902e8e4133cab085137f5b9", "fullName": "tests.test_create_courier.TestCreateCourier#test_create_same_courier_data", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_courier"}, {"name": "subSuite", "value": "TestCreateCourier"}, {"name": "host", "value": "MacBook-Pro-Petr.local"}, {"name": "thread", "value": "19998-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_courier"}]}