{"name": "Проверка возвращаемого кода 409 при создании курьера с уже существующим логином", "status": "failed", "statusDetails": {"message": "AssertionError: assert (409 == 409 and 'Этот логин у...буйте другой.' == 'Этот логин уже используется'\n +  where 409 = <Response [409]>.status_code\n  \n  - Этот логин уже используется\n  + Этот логин уже используется. Попробуйте другой.)", "trace": "self = <test_create_courier.TestCreateCourier object at 0x11025a720>, register_new_courier = <Response [201]>\ncreate_courier_data = {'firstName': 'pho6pqurae', 'login': 'fdogz20da6', 'password': '4zu1z12195'}\n\n>   ???\nE   AssertionError: assert (409 == 409 and 'Этот логин у...буйте другой.' == 'Этот логин уже используется'\nE    +  where 409 = <Response [409]>.status_code\nE     \nE     - Этот логин уже используется\nE     + Этот логин уже используется. Попробуйте другой.)\n\n/Users/flowforme/stud/pythonProject/tests/test_create_courier.py:29: AssertionError"}, "start": 1723291438429, "stop": 1723291438818, "uuid": "c9ecdea9-7c0f-4618-8358-b3d2e957ea00", "historyId": "6df1151fa32767c3c24301aa48e366a1", "testCaseId": "6df1151fa32767c3c24301aa48e366a1", "fullName": "tests.test_create_courier.TestCreateCourier#test_create_same_courier_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_courier"}, {"name": "subSuite", "value": "TestCreateCourier"}, {"name": "host", "value": "MacBook-Pro-Petr.local"}, {"name": "thread", "value": "19998-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_courier"}]}